---

- name: update apt-cache
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - common_install

- name: upgrade the distro
  apt: upgrade=yes
  tags:
    - common_install

- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git
    - curl
    - zip
    - unzip
    - wget
  tags:
    - common_install

- name: create locale
  locale_gen: name={{ app_locale }} state=present
  tags:
    - common_install
    - common_install_locale

- name: set default locale
  command: "/usr/sbin/update-locale LANG={{ app_locale }}"
  tags:
    - common_install
    - common_install_locale
