---

dependencies:
  - role: pjan.vandaele.postgresql
    postgresql_version: 9.3
    postgresql_ext_install_dev_headers: yes
    postgresql_databases:
      - name: "{{ app_db_name }}"
    postgresql_users:
      - name: "{{ app_db_user }}"
        pass: "{{ app_db_password }}"
        encrypted: no
    postgresql_user_privileges:
      - name: "{{ app_db_user }}"
        db: "{{ app_db_name }}"
        priv: "ALL"
    tags:
      - db_install
