---

- name: common | create admin group
  group: name=admin state=present
  tags:
    - base_user

- name: common | create app user group
  group: name={{ app_user }} state=present
  tags:
    - base_user

- name: common | create user
  user: name="{{ app_user }}"
        groups=admin,{{ app_user }}
        home="{{ app_user_home }}"
        shell=/bin/bash
        state=present
  tags:
    - base_user

- name: common | add admin group to sudoers
  lineinfile: dest=/etc/sudoers state=present
              regexp='^%ADMIN ALL\='
              line='%ADMIN ALL=(ALL) NOPASSWD:ALL'
              validate='visudo -cf %s'
  tags:
    - base_user
